print(5>4 or 6<3)
print(47<754 or 6>73)
print(7528<8263 or 75<826)
print(63<72 or 82>926)
print(282==82 or 6121>872)
print(73<12 and 84>93)
print(8473>83 and 12>122)
print(7373<72693 and 91<12)
print(83653652==82728 and 283>8272)
print(83682<922 and 72162==8621)

#sequecing_ aris tanmidevroba magalitad ro shevadarot adamianebis rigi
#interation_aris gameoreba raRaca rac wreze dadis mudmivad
#selection_aris archeva 



for i in range(10):
    print("gio")
#es terminalsgin gamoitans tanmimdevrobit daweril sityva gios

#for ioop_ aris punqcia romelic chven mier daweril sityvas imeorebs ramdenjerac gvinda amit tavidan vicilebt bevri codis ertad daweras

#range()_ am punqciashi mititebuli ricxvi terminalshi gaameorbs ertidaigive sityvas imdenjer ramdenjerac chven gvinda

for i in range(10):
    print("BMW")

for i in range(100):
    print("manjgaladze")

for i in range(46):
    print("lurji")

for i in range(32):
    print("G")

A1 = (input("shemoitane rame"))
A2 = (input("shemoitane rame"))
A3 = (input("shemoitane rame"))
A4 = int(input("shemoitane ricxvi"))
print(str(A4)+A1+A2+A3)

A1 = "5"
A2 = 5
A3 = 5.455
A4 = True
print(type(A1))
print(type(A2))
print(type(A3))
print(type(A4))

A1 = int(input("semoitane ricxvi"))
A2 = int(input("semoitane ricxvi"))
A3 = int(input("semoitane ricxvi"))
A4 = int(input("semoitane ricxvi"))
print(A1+A2+A3+A4)