#cven viswavlet shedarebis operatorebi:mag <_metia, >_naklebia, ==_tolia

A1 = int(input("semoitane ricxvi"))
A2 = int(input("semoitane meore ricxvi"))
print(A1>A2)
print(A1<A2)
print(A1==A2)

A1 = (input("shemoitane stringi"))
A2 = (input("shemoitane stringi"))
A3 = (input("shemoitane stringi"))
A4 = (input("shemoitane stringi"))
A5 = (input("semoitrane stringi")) 
print(A1+A2+A3+A4+A5)

A1 = int(input("semoitane ricxvi"))
A2 = int(input("semoitane ricxvi"))
A3 = int(input("shemoitane ricxvi"))
A3 = int(input("shemoitane ricxvi"))
A4 = int(input("shemoitane ricxvi"))
A5 = (A1+A2+A3+A4)
print(A5/5)

A1 = "gio"
A2 = 14
A3 = 1.76
A4 = True
print(type(A1))
print(type(A2))
print(type(A3))
print(type(A4))

A1 = (input("shemoitane stringi"))
A2 = (input("shemoitane stringi"))
print(A1==A2)

A1 = int(input("shemoitane ricxvi"))
A2 = int(input("shemoitane ricxvi")) 
A3 = int(input("shemoitane ricxvi")) 
A4 = int(input("shemoitane ricxvi")) 
print(A1+A2+A3+A4)

a1 = 58
a2 = 54
a3 = 65
print(58)
print(54)
print(65)
A1 = (input("shemoitane a1"))
A2 = (input("shemoitane a2")) 
A3 = (input("shemoitane a3")) 
print(A1+A2+A3)


